### DISCUSSION TITLE
Cron jobs marked as failed

### DISCUSSION THREAD

**Discussion by corvus-ch** [wavelog/wavelog#1076] [Q&A] [answered]
I do host an instance of Wavelog (version 1.8.6) using docker. All cron jobs, expect for the ones that are pending, are marked as failing. Where can I find logs or other debug information to identify what the issue is? Docker logs only show me the Apache access log but nothing more.

Is there a way to manually trigger a job in isolation the same way as cron would?

**Comment by winnieXY** [comment]
I also use docker for wavelog. Could you please post your command line arguments while starting (or your docker-compose file?).

**Comment by corvus-ch** [comment]
Its Docker Compose. I used https://github.com/wavelog/wavelog/wiki/Installation-via-Docker#docker-composeyaml as a foundation and extended it for Traefik to handle ingress, and added some automated backup.

```yaml
---
services:
  wavelog-db:
    image: mariadb:11
    container_name: wavelog-db
    environment:
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: *****
      MARIADB_ROOT_PASSWORD: *****
    volumes:
      - wavelog-dbdata:/var/lib/mysql
    restart: unless-stopped

  wavelog-main:
    container_name: wavelog-main
    image: ghcr.io/wavelog/wavelog:latest
    depends_on:
      - wavelog-db
    environment:
      CI_ENV: docker
    volumes:
      - wavelog-config:/var/www/html/application/config/docker
      - wavelog-uploads:/var/www/html/uploads
      - wavelog-userdata:/var/www/html/userdata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wavelog.rule=Host(`*****`)"
    restart: unless-stopped

  backup:
    image: codeberg.org/corvus-ch/restic-cron
    hostname: wavelog
    environment:
      - RESTIC_PASSWORD_FILE=/run/secrets/restic_password
      - RESTIC_REPOSITORY=rest:https://wavelog:${RESTIC_REST_PASSWORD}@*****/wavelog
      - RESTIC_PIPE_CMD=mariadb-dump --host=wavelog-db --user=wavelog --password=***** --single-transaction wavelog
      - CRON_SCHEDULE=23 2 * * *
    volumes:
      - wavelog-uploads:/data/uploads:ro
      - wavelog-userdata:/data/userdata:ro
      - wavelog-config:/data/config:ro
    secrets:
      - restic_password
    restart: unless-stopped

secrets:
  restic_password:
    file: .restic_password

volumes:
  wavelog-dbdata:
  wavelog-uploads:
  wavelog-userdata:
  wavelog-config:
```
