### DISCUSSION TITLE
Adding cron jobs - Docker container

### DISCUSSION THREAD

**Discussion by amhyder** [wavelog/wavelog#1917] [Q&A] [answered]
Hello, I am currently on the latest release of wavelog deployed in the provided docker container. I noticed under the admin settings I see the Cron Manager interface. The Master Cron status is reporting as OK and I have 4 cron jobs listed in the table below:
- clublog_download
- update_update_hamsofnote
- update_update_tle
- update_version_check

I noticed in the docs there are numerous other cron jobs recommended for keeping various pieces of wavelog data up to date. Since the UI does not support adding cron jobs, I went into the container, ran `crontab -e` and saw my master cron job displayed at the top of the file. I added the recommended cron jobs to this crontab file and can see that they are running as expected.

Are these manually added cron jobs supposed to show in the admin Cron Manager interface? It's been approximately 24hours since ive made the change and numerous jobs I manually added have successfully run. Is this behavior expected?

**Comment by HB9HIL** [comment]
Hello @amhyder 

Question: You should way more cronjobs then just those four. The other cronjobs are disable by default but you can enable them with just one mouse click. 

![grafik](https://github.com/user-attachments/assets/bf4a9be8-8d9f-4e02-88d2-36a6a4b4ceb8)

**Comment by HB9HIL** [comment]
You should see in total 17 Cronjobs, which are partially enabled or disabled by default. Enable them with a click on the On/Off Switch on the far right side. 

![grafik](https://github.com/user-attachments/assets/52d31a8c-b2c4-4b3e-8292-bb6ed6e27fd8)

About your manual modification inside the container: Your manually edited crontab won't last long. You will notice that these things get overwritten when upgrading the container. (`docker compose down`, `docker compose pull`, `docker compose up -d`)

**Reply by HB9HIL** [reply]
PS: Adding new Cronjobs via WebUI is currently not supported.. For reasons

**Reply by amhyder** [reply]
Hi @HB9HIL thanks for your reply. I only have 4 entries in the table. Is there somewhere I can check to see why the other cron jobs are not listed. Thanks!

![image](https://github.com/user-attachments/assets/b53612fc-25a2-4c9b-9083-9b4c3ed5103d)

**Reply by HB9HIL** [reply]
Please show me a full screenshot of the debug page and a copy of your docker compose file. 73

**Reply by amhyder** [reply]
Sorry for the delay. Here's the requested info:
![Capture](https://github.com/user-attachments/assets/f76877a5-bbc6-4e8d-80d0-a27e27f790a8)


Docker Compose
```
version: '3'
services:
  wavelog-db:
    image: mariadb:11.3
    container_name: wavelog-db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: <REDACTED>
    volumes:
      - wavelog-dbdata:/var/lib/mysql
    restart: unless-stopped

  wavelog-main:
    container_name: wavelog-main
    image: ghcr.io/wavelog/wavelog:latest
    depends_on:
      - wavelog-db
    environment:
      CI_ENV: docker
    volumes:
      - wavelog-config:/var/www/html/application/config/docker
      - wavelog-uploads:/var/www/html/uploads
      - wavelog-userdata:/var/www/html/userdata
    ports:
      - "8086:80"
    restart: unless-stopped

volumes:
  wavelog-dbdata:
  wavelog-uploads:
  wavelog-userdata:
  wavelog-config:
```
