### DISCUSSION TITLE
Docker

### DISCUSSION THREAD

**Discussion by enzo2** [wavelog/wavelog#192] [General]
I see it is stated that support will not be provided for Docker. (This verbiage was apparently brought over with the fork.) I think this would be a way to distinguish wavelog and make it accessible to a larger audience. It has become quite common to use a home server or NAS to run various containers, thereby keeping all of one's personal services centralized for easier installation/updating/management and better security. This would also allow users to upgrade on a stable release channel rather than git pulling from the master branch at random times. 

I was able to get it working by creating a docker-compose.yml, Dockerfile and docker-entrypoint.sh. However, it's my first time using the latter two, so I will refrain from posting them yet unless someone wants to see it. I still have not added cron job handling and backups.

**Comment by int2001** [comment]
Do you want to share your achievements?

tbh: We're experimenting with docker, too. But it is still far away from release. We've still no real plans to support docker in our master-branch, but we're not afraid of an experimental usage for docker (without support)

**Comment by enzo2** [comment]
Thanks, here is what I have. 

<details>
  <summary>docker-compose.yml</summary>

  ```
  services:
    mysql:
      container_name: wavelog-mysql
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: xxxxxxxxxxx   #create your own pw
        MYSQL_DATABASE: wavelog
        MYSQL_USER: waveloguser
        MYSQL_PASSWORD: xxxxxxxxxx  #create your own pw
      volumes:
        - mysql-db-wavelog:/var/lib/mysql        # Persisting MySQL data
      ports:  #should probably change to 'expose' as no need to publish to machine
        - "3306:3306"  
      restart: always
      
    # PHP and Apache Service
    app:
      container_name: wavelog
      build: ./php-apache    #this folder should include Dockerfile and docker-entrypoint.sh
      ports:
        - "5000:80"
      volumes:
        - ./volumes/wavelog:/var/www/html   #mount a directory so we can see our files easily
      depends_on:
        - mysql
      restart: always
  volumes:
    mysql-db-wavelog:
  ```
</details>


<details>
  <summary>Dockerfile</summary>

  ```
  FROM php:8.2-apache

  # Update package repository and install git
  RUN apt-get update && apt-get install -y git
  RUN git config --global --add safe.directory /var/www/html

  # install php extensions
  RUN apt-get install -y libzip-dev 
  RUN docker-php-ext-install zip mysqli pdo pdo_mysql
  RUN apt-get clean && rm -rf /var/lib/apt/lists/*
    
  # Copy the entrypoint script
  COPY docker-entrypoint.sh /usr/local/bin/
  RUN chmod +x /usr/local/bin/docker-entrypoint.sh
  ENTRYPOINT ["docker-entrypoint.sh"]

  #Add settings required by wavelog
  RUN { \
      echo 'max_execution_time=601'; \
      echo 'upload_max_filesize=9M'; \
      echo 'post_max_size=9M'; \
  } > /usr/local/etc/php/conf.d/custom.ini

  CMD ["apache2-foreground"]
  ```
</details>


<details>
  <summary>docker-entrypoint.sh</summary>

  ```
  #!/bin/bash
  set -e

  REPO_DIR="/var/www/html"
  GIT_REPO="https://github.com/wavelog/Wavelog.git"
  EXPECTED_USER="www-data"

  # Ensure the expected user owns the directory before git operations
  if [ ! -d "$REPO_DIR/.git" ]; then
      # Clean directory if .git doesn't exist
      rm -rf $REPO_DIR/*
      git clone $GIT_REPO $REPO_DIR
  else
      # Make sure we're in the right directory
      cd $REPO_DIR
      # Stash any changes including untracked files
      git stash push --include-untracked
      git pull --rebase
      # Apply the stashed changes back
      git stash pop || true # Ignore errors in case nothing was stashed
  fi

  # Ensure correct ownership for all operations
  chown -R $EXPECTED_USER:$EXPECTED_USER $REPO_DIR
  chmod -R g+rw $REPO_DIR

  # Execute the CMD
  exec "$@"
  ```
</details>
