### DISCUSSION TITLE
Allow to specific running UID/GID in docker environment?

### DISCUSSION THREAD

**Discussion by ludoux** [wavelog/wavelog#1972] [Ideas]
Hi, I'm using Unraid to deploy docker applications. I used to set the UID/GID env (or use `--user` args) to keep the files/folders permission same as other files and folders. However, the wavelog's dockerfile force to use `root:www-data` and can't change its id. I'm wondering if wavelog official docker image will provide some ENVs to allow user to specific the UID and GID which can make users customize the files and folders owners id in the future. Thank you :)

**Comment by EricZimmerman** [comment]
This needs done 100 percent. It's so annoying as is to be forced to use groups you can't manage properly in some cases.

**Comment by HB9HIL** [comment]
Well it's possible already today. This is the part of my dev setup

```yaml
  wavelog-main:
    container_name: wavelog-main
    build: .
    depends_on:
      - wavelog-db
    environment:
      CI_ENV: docker
      HOST_UID: "1000"
    ports:
      - "8086:80"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
    networks:
      - wavelog-network
    command: >
      bash -c "
        usermod --non-unique -u $$HOST_UID www-data &&
        groupmod --non-unique -g $$HOST_UID www-data &&
        [ -f /var/www/html/.htaccess ] || cp /var/www/html/htaccess.sample /var/www/html/.htaccess &&
        mkdir -p /var/www/html/application/config/docker &&
        /usr/local/bin/apache2-foreground
      "
```
      
But as this was requested already several times I'll see what I can offer/do

**Comment by EricZimmerman** [comment]
It's both pieces tho. User and group, and on the database side as well plus the www-data folders for PHP. That bash snippet is helpful tho

If permission is wrong wavelog thinks it needs reinstalled.and starts the wizard again.

**Reply by HB9HIL** [reply]
> If permission is wrong wavelog thinks it needs reinstalled.and starts the wizard again.

look. we have an official docker compose in our documentation [here](https://docs.wavelog.org/getting-started/installation/docker/). This is what we support at the moment. If something doesn't work it's likely because the user modified something. I assume you can understand that we can't offer support for every possible case.

**Reply by HB9HIL** [reply]
And regading database: A container is an isolated environment. If you use proper volume mounts or don't touch filepermissions in bind mounts everything is running just fine as it should be. We not gonna reduce security as price for customization. You may understand tho

**Reply by EricZimmerman** [reply]
I get it. It's your project but it makes it harder to use on systems like unraid and truenas as a packaged app.

**Reply by HB9HIL** [reply]
Already working on the wavelog container stuff. Hang tight

But to be prepared: There won't be any solution for you for the mariadb container as we don't manage this one. There you have to find a solution yourself

**Comment by EricZimmerman** [comment]
for future users, consider this for maria, which does allow UID and GID to be specified. i havent tried it yet, but it is a bit old

https://github.com/cynici/docker-mariadb

**Comment by HB9HIL** [comment]
@ludoux @EricZimmerman 

Do me a favor and test this image: `ghcr.io/hb9hil/wavelog:docker_env`

Set `PUID` and `PGID` to your liking

**Comment by EricZimmerman** [comment]
Here is an up to date maria DB that allows changes to ids. 

https://docs.linuxserver.io/images/docker-mariadb/

In my experience all the images from that location are exceptional 

I will test out the other image asap.

**Comment by EricZimmerman** [comment]
i tried the env image on a new install and it just kept redirecting to install over and over and over, adding a new install every time

install
install\install
install\install\install

and so on.

the mariadb thing DOES work as any user you want, just make sure you map a bind mount to the /config dir

**Comment by EricZimmerman** [comment]
i DID see in the processes list while  the container was running that it was doing some chown calls, but it was still using  the old root:www-data that i saw (via dockhand).

i got it working with a wholly new install after starting everything over, but now i see this in step 2, after changing my owner:group to apps


<img width="1662" height="1104" alt="image" src="https://github.com/user-attachments/assets/39b73dd8-9ed2-40a1-9c8f-5cee78f3a559" />

Reverting back to the current wavelog release, i get this:

<img width="1662" height="1104" alt="image" src="https://github.com/user-attachments/assets/fd7938e2-7508-43a3-8494-734b566687ea" />

so it seems the test docker_env option is missing some php modules?

**Reply by HB9HIL** [reply]
Wtf..

This is super odd

Can you show me your docker-compose? Docker Config?

**Reply by HB9HIL** [reply]
PS: You will still see "root:www-data" in the logs but the user is remapped and the new entrypoint is handling the overwrite user. Yous as info. I was able to reproduce the missing php modules for a short moment, but I have no idea yet why this happens. Show me your docker config stuff please so I can compare

**Reply by HB9HIL** [reply]
@EricZimmerman I think I found the issue and fixed some stuff. Repull the image `ghcr.io/hb9hil/wavelog:docker_env` and tell me whats going on now

EDIT: Not ready yet. there is a bug in a upstream source which I need to get fixed first

**Reply by HB9HIL** [reply]
https://github.com/wavelog/wavelog/pull/3304

**Reply by HB9HIL** [reply]
@EricZimmerman now you can test again. Repull the image

**Comment by EricZimmerman** [comment]
This has the main image in use but otherwise it's as is. 

The extra maria variables were from testing the Linux server version, but otherwise it's stock wavelog docker compose with binds 
```
services:
  wavelog-db:
    #image: mariadb:latest
    image: lscr.io/linuxserver/mariadb:latest
    container_name: wavelog-db
    environment:
      - PUID=568
      - PGID=568
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=wavelog
      - MARIADB_USER=wavelog
      - MARIADB_PASSWORD=xxx
      - MARIADB_ROOT_HOST="%" 
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_DATABASE=wavelog #optional
      - MYSQL_USER=wavelog #optional
      - MYSQL_PASSWORD=xxx #optional
      - MARIADB_AUTO_UPGRADE=true
    volumes:
      
      - /mnt/tank/configs/wavelog/data/:/config
    restart: unless-stopped

  wavelog-main:
    container_name: wavelog-main
    image: ghcr.io/wavelog/wavelog:latest
    #image: ghcr.io/hb9hil/wavelog:docker_env
    depends_on:
      - wavelog-db
    environment:
      - CI_ENV=docker
      - PUID=568
      - PGID=568
    volumes:
      - /mnt/tank/configs/wavelog/config:/var/www/html/application/config/docker
      - /mnt/tank/configs/wavelog/uploads:/var/www/html/uploads
      - /mnt/tank/configs/wavelog/userdata:/var/www/html/userdata
    ports:
      - 8086:80
    restart: always
```

**Comment by EricZimmerman** [comment]
here is the latest.

<img width="1624" height="1083" alt="image" src="https://github.com/user-attachments/assets/e4e68b5a-8e66-4865-a6f0-2812eedcfe1f" />


it didnt honor the permissions on the config dir and changed them to root:apps when it started out as apps:apps

resetting the permissions in the  shell and starting the container over resulted in a clean install


i deleted the container and any local images so it would be repulled. the calls like:

```
chown -R root:www-data /var/www/html/assets
```

seem to take a while on startup, but then the installer is available. it  would be nice to see some stuff in the logs vs watching processes as to progress during initialization, etc. 

even if i in the logs there was a call to "initializing installer" and  then when its ready "Installer ready. connect to http:XXX/install to proceed" or something so people do not hit the url and port and wonder why nothing is showing up.

once i reset permissions in the shell and restarted the container, this is how it looked:

<img width="1624" height="1083" alt="image" src="https://github.com/user-attachments/assets/3145d7b3-1a7d-460e-85e2-16d6d90691df" />

**Comment by EricZimmerman** [comment]
it also seems that lscr.io/linuxserver/mariadb:latest works just fine with wavelog. no issues at all once it spun up

**Comment by EricZimmerman** [comment]
<img width="1624" height="1603" alt="image" src="https://github.com/user-attachments/assets/84d361ac-dee1-422e-bd9e-3e09f1129de3" />

**Comment by EricZimmerman** [comment]
after running through a new installation, stopping the stack, then copying all my old data from existing wavelog to the wavelog dirs, and  the database to the new database location, then changing permission across the board to apps:apps, everything is now restored and looks good. all old data is accounted for:

<img width="1723" height="1732" alt="image" src="https://github.com/user-attachments/assets/fdccb501-b569-48fe-839d-2044359fa63d" />

**Comment by HB9HIL** [comment]
@EricZimmerman So it works. What you probably missed in the beginning: Changing the docker-compose.yml at runtime has no effect until you `--force-recreate` the container or `docker compose down && docker compose up -d` it. I have no idea how this works in your GUI. 

> it would be nice to see some stuff in the logs vs watching processes as to progress during initialization, etc.

this is not possible in this case as it's the first requests. It's still a PHP webapplication and it depends hardly on the hardware you run this on. So no solution here. 

> even if i in the logs there was a call to "initializing installer" and then when its ready "Installer ready. connect to http:XXX/install to proceed" or something so people do not hit the url and port and wonder why nothing is showing up.

The installer checks for 
- missing config.php
- missing database.php
- missing installer lockfile
If all there are true you will be redirected instant to the installer. The chown runs already on container startup. So if you run on slow hardware and directly call the URL this might occur that you have to wait a few seconds. (Unraid/Truenas are NAS and not really designed to run containers, even they can tho). 

test it a few days and report back please

**Reply by HB9HIL** [reply]
thx for alpha testing here at this point

**Reply by HB9HIL** [reply]
One more recommendation: You have `file` as primary cache adapter configured. I highly recommend `apcu` (works without any other components) or `redis`/`memcached` for caching. Especially on the dxcluster with both dxcluster caching options in config.php enabled (default `false`) you'll experience a much faster setup.

**Reply by HB9HIL** [reply]
Also in general: consider updating your config.php from time to time based on https://github.com/wavelog/wavelog/blob/master/application/config/config.sample.php

**Reply by EricZimmerman** [reply]
Ok. I'll update what I have from that example config and switch to redis. 

Thanks for the tip.

**Reply by HB9HIL** [reply]
Add a Valkey (better opensource alternative to Redis) to your docker-compose.yml

```yaml
  wavelog-cache:
    image: valkey/valkey:8-alpine
    container_name: wavelog-cache
    restart: unless-stopped
    volumes:
      - wavelog-cachedata:/data
```

The create the `redis.php` based on `redis.sample.php`

```php
<?php
/*
| -------------------------------------------------------------------------
| Redis settings
| -------------------------------------------------------------------------
| Copy this sample file to redis.php and set your settings as needed.
|
|       See: https://codeigniter.com/userguide3/libraries/caching.html#redis-caching
|
*/

// Connection type: 'tcp' for TCP/IP, 'unix' for Unix domain sockets
$config['socket_type'] = 'tcp';

// Redis server hostname / IP address
$config['host'] = 'wavelog-cache';

// Redis server port (default: 6379)
$config['port'] = 6379;

// Redis authentication password (NULL if no password required)
$config['password'] = NULL;

// Unix domain socket path (only used if socket_type is set to 'unix')
// Example: '/var/run/redis.sock'
$config['socket'] = '/var/run/redis.sock';

// Connection timeout in seconds (0 = no timeout)
$config['timeout'] = 0;

// Redis database number (0-15 by default)
// Useful for separating different applications or data types
$config['database'] = 1;
```

in your `config.php`:
```php
# ...
$config['cache_adapter'] = 'redis';
# ...
```
