### DISCUSSION TITLE
Development Enviroment

### DISCUSSION THREAD

**Discussion by desertblade** [wavelog/wavelog#877] [General]
I created a docker developer instance using docker to speed up dev time.  It builds the docker container and any changed to the files will be synced to the docker instance and available instantly.  This was much easier than trying to install a WAMP/LAMP.  Figure I would share, might help someone else.

Ideally there would be a static SQL db, maybe next iteration I will look into it. 

Place this docker-compase-dev.yml in the root directory of wavelog and run with _**docker-compose -f docker-compose-dev.yml watch**_

```
# Docker Compose for Local Development! Not for general use
# run with: docker-compose -f docker-compose-dev.yml watch

services:
  dev-wavelog-ui:
    build: .
    ports:
      - "8088:80"
    volumes:
      - dev-wavelog-config:/var/www/html/application/config/docker
      - dev-wavelog-uploads:/var/www/html/uploads
      - dev-wavelog-userdata:/var/www/html/userdata
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html/application

  dev-wavelog-db:
    image: mariadb:11.3
    container_name: dev-wavelog-db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: wavelog # <- Insert a strong password here
    volumes:
      - dev-wavelog-dbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  dev-wavelog-dbdata:
  dev-wavelog-uploads:
  dev-wavelog-userdata:
  dev-wavelog-config:
```

**Comment by desertblade** [comment]
If any of the core team sees this...I was thinking the demo database might be the right development dataset to work against.  It would be fairly easy to spin up a MariaDB and add a script to seed the data. 

Side note: I tested this on Windows and Mac, both system live update. This may be my new favorite way for dev environments. To start fresh you just blow away the volumes in Docker Desktop.

**Reply by int2001** [reply]
That's indeed nice.
I develop in a similar manner.
Not with sync, but with a bind-volume for the webroot.

The files *are* the same files which are being used by the docker-webserver.

If you're interested i can share the docker-compose.yaml

Without sync it's much faster and you can use your favorite IDE.

Bonus: php-debugger works as well with that setup.

**Reply by desertblade** [reply]
I would like to see it. I initially tried mapping the folder to the docker, which I ran into issues. I remembered reading about the using Watch so it was cool to see it in action.

My setup still allows me to use the IDE on the host system and does make it portable between my systems. 

I am not a fan of using Docker Volumes in my home lab "Prod" environment.  I prefer using folders that I can easily rsync to my NAS,, then backup to the cloud w/versioning. It also makes it easier to port to another docker host if needed. Just copy the backup folder that has the data and docker-compose to the new host. I figured it out with Wavelog, but it felt like a hack. Your docker-compose may help me figure out a better solution.

Really like wavelog and props to the awesome community!!

**Reply by int2001** [reply]
no problem. Besides not using sync and PHP-Debugger it's the same.
You can rsync here as well.

Structure:
Have a folder with:
- docker-compose.yaml (see below)
- a subfolder where you clone the wavelog-repo into (via `git clone`)

Files:
docker-compose.yaml:
```
version: '3'
services:
  wavelog-db:
    image: mariadb:11.3
    container_name: wavelog-db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: wavelog
      MARIADB_USER: wavelog
      MARIADB_PASSWORD: wavelog # <- Insert a strong password here
    volumes:
      - wavelog-dbdata:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "23306:3306"

  wavelog-main:
    container_name: wavelog-main
    build:
      context: ./wavelog/
      dockerfile: ./Dockerfile
    depends_on:
      - wavelog-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - wavelog-backup:/var/www/html/application/backup
      - wavelog-uploads:/var/www/html/application/uploads
      - ./wavelog:/var/www/html
    environment:
     XDEBUG_MODE: debug
     XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
     VAR_DUMPER_FORMAT: server
     VAR_DUMPER_SERVER: "host.docker.internal:9912"
    ports:
      - "8086:80"
    restart: unless-stopped

volumes:
  wavelog-dbdata:
  wavelog-backup:
  wavelog-uploads:
```

Fire `docker-compose up -d`
You can now work (on your host) within `./wavelog`. All changes take immediatly place because docker uses those files directly.

There are many different ways how to achieve it. Your's one is nice as well with the sync.
