### DISCUSSION TITLE
Docker Folder Write Permissions

### DISCUSSION THREAD

**Discussion by rogmet** [wavelog/wavelog#989] [Q&A] [answered]
Sorry folks, I'm scratching my head on this one, can anybody help please? I am installing via a docker-compose file alongside numerous other containers such as Home Assistant. On the Wavelog volumes specified in the docker-compose file, all of them give a Folder Write Permissions error in the installer; /application /uploads and /userdata all fail.
It's on Ubuntu 24.04.1 Server. Would anyone know what's going on?

**Comment by HB9HIL** [comment, marked as answer]
Did you use the provided docker-compose as it is described in our wiki?

**Reply by rogmet** [reply]
Hi,
I changed it a bit to fit in with my current config, I have mariadb (container name mysql) on there already for example and I have absolute references to the config folders (though this looks suspicious in light of what is failing). It looks like this:
```
   wavelog:

   container_name: wavelog
    image: ghcr.io/wavelog/wavelog:latest
    depends_on:
      - mysql
    environment:
      CI_ENV: docker
    volumes:
      - /home/rogmet/docker/wavelog/wavelog-config:/var/www/html/application/config/docker
      - /home/rogmet/docker/wavelog/wavelog-uploads:/var/www/html/uploads
      - /home/rogmet/docker/wavelog/wavelog-userdata:/var/www/html/userdata
    ports:
      - "8086:80"
    restart: unless-stopped
```
The volumes as listed in the wiki docker-compose are in there too.
